import { readFileSync, writeFileSync, readdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..", "..", "..");
const CMS_API = join(ROOT, "apps", "cms", "src", "api");
const CMS_COMPONENTS = join(ROOT, "apps", "cms", "src", "components");
const OUTPUT = join(ROOT, "apps", "web", "src", "lib", "strapi.types.ts");

function toPascalCase(str) {
  return str
    .split(/[-_\s.]+/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

function toInterfaceName(singularName) {
  return toPascalCase(singularName);
}

function toComponentInterfaceName(category, name) {
  return toPascalCase(category) + toPascalCase(name) + "Component";
}

const STRAPI_TYPE_MAP = {
  string: "string",
  text: "string",
  email: "string",
  richtext: "string",
  password: "string",
  integer: "number",
  biginteger: "number",
  float: "number",
  decimal: "number",
  boolean: "boolean",
  date: "string",
  datetime: "string",
  time: "string",
  json: "Record<string, unknown>",
  media: "{ url: string; alternativeText?: string }",
};

function isRequired(attr) {
  return attr.required === true;
}

function strapiTypeToTS(attr) {
  const { type } = attr;

  if (!type) {
    console.warn("  ⚠ attribute missing `type`:", JSON.stringify(attr));
    return "unknown";
  }

  let tsType = "unknown";

  if (STRAPI_TYPE_MAP[type]) {
    tsType = STRAPI_TYPE_MAP[type];
  } else if (type === "enumeration") {
    if (!attr.enum) tsType = "string";
    else tsType = attr.enum.map((v) => `"${v}"`).join(" | ");
  } else if (type === "component") {
    const [category, name] = attr.component.split(".");
    const compName = toComponentInterfaceName(category, name);
    tsType = attr.repeatable ? `${compName}[]` : compName;
  } else if (type === "relation") {
    if (!attr.target) {
      console.warn("  ⚠ relation attribute missing `target`:", JSON.stringify(attr));
      return "unknown[]";
    }
    const [, targetName] = attr.target.split(".");
    const ifaceName = toInterfaceName(targetName);
    if (attr.relation === "oneToMany" || attr.relation === "manyToMany") {
      return `${ifaceName}[]`;
    }
    return `${ifaceName} | null`;
  }

  if (!isRequired(attr)) {
    if (!tsType.endsWith("]")) {
      tsType += " | null";
    }
  }

  return tsType;
}

function readJSON(filePath) {
  return JSON.parse(readFileSync(filePath, "utf-8"));
}

function collectComponents() {
  const components = {};
  const categories = readdirSync(CMS_COMPONENTS);
  for (const category of categories) {
    const categoryPath = join(CMS_COMPONENTS, category);
    if (!existsSync(categoryPath)) continue;
    const files = readdirSync(categoryPath).filter((f) => f.endsWith(".json"));
    for (const file of files) {
      const name = file.replace(".json", "");
      const schema = readJSON(join(categoryPath, file));
      components[`${category}.${name}`] = { ...schema, _category: category, _name: name };
    }
  }
  return components;
}

function collectContentTypes() {
  const types = {};
  const apiDirs = readdirSync(CMS_API);
  for (const dir of apiDirs) {
    const ctDir = join(CMS_API, dir, "content-types");
    if (!existsSync(ctDir)) continue;
    const ctItems = readdirSync(ctDir);
    for (const item of ctItems) {
      const schemaPath = join(ctDir, item, "schema.json");
      if (!existsSync(schemaPath)) continue;
      const schema = readJSON(schemaPath);
      types[schema.info.singularName] = schema;
    }
  }
  return types;
}

function generate() {
  console.log("Collecting components from", CMS_COMPONENTS, "...");
  const components = collectComponents();
  console.log(`  ✓ ${Object.keys(components).length} components found`);
  console.log("Collecting content types from", CMS_API, "...");
  const contentTypes = collectContentTypes();
  console.log(`  ✓ ${Object.keys(contentTypes).length} content types found`);

  const lines = [];
  lines.push("// Auto-generated by scripts/generate-types.mjs — do not edit manually");
  lines.push("// Run: pnpm --filter web generate:types");
  lines.push("");

  // --- Base document interface ---
  lines.push("interface StrapiDocument {");
  lines.push("  id: number;");
  lines.push("  documentId: string;");
  lines.push("  createdAt: string;");
  lines.push("  updatedAt: string;");
  lines.push("  publishedAt: string;");
  lines.push("}");
  lines.push("");

  // --- Component interfaces ---
  for (const [_, comp] of Object.entries(components)) {
    const ifaceName = toComponentInterfaceName(comp._category, comp._name);
    lines.push(`export interface ${ifaceName} {`);
    lines.push("  id: number;");
    for (const [attrName, attr] of Object.entries(comp.attributes)) {
      const tsType = strapiTypeToTS(attr, contentTypes, components);
      lines.push(`  ${attrName}: ${tsType};`);
    }
    lines.push("}");
    lines.push("");
  }

  // --- Content type interfaces ---
  for (const [singularName, schema] of Object.entries(contentTypes)) {
    const ifaceName = toInterfaceName(singularName);
    lines.push(`export interface ${ifaceName} extends StrapiDocument {`);
    for (const [attrName, attr] of Object.entries(schema.attributes)) {
      const tsType = strapiTypeToTS(attr, contentTypes, components);
      lines.push(`  ${attrName}: ${tsType};`);
    }
    lines.push("}");
    lines.push("");
  }

  // --- Response metadata ---
  lines.push("interface ResponseMeta {");
  lines.push("  pagination?: {");
  lines.push("    page: number;");
  lines.push("    pageSize: number;");
  lines.push("    pageCount: number;");
  lines.push("    total: number;");
  lines.push("  };");
  lines.push("}");
  lines.push("");

  // --- Response wrappers ---
  lines.push("export type SingleResponse<T> = { data: T; meta: ResponseMeta };");
  lines.push("export type CollectionResponse<T> = { data: T[]; meta: ResponseMeta };");

  writeFileSync(OUTPUT, lines.join("\n") + "\n");
  console.log(`✓ Generated types written to ${OUTPUT}`);
}

generate();
