import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} [&>header]:p-6 [&>header]:border [&>*>section]:p-6 [&>*>section]:border [&>*>section>article:not(:first-child)]:mt-3 `}
      >
        {children}
      </body>
    </html>
  );
}
