// Auto-generated by scripts/generate-types.mjs — do not edit manually
// Run: pnpm --filter web generate:types

interface StrapiDocument {
  id: number;
  documentId: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
}

export interface ArrayLinkComponent {
  id: number;
  label: string;
  href: string;
}

export interface ArrayListComponent {
  id: number;
  item: string;
}

export interface SingleOrganizationComponent {
  id: number;
  name: string;
  location: string;
  from: string;
  to: string | null;
}

export interface Certification extends StrapiDocument {
  name: string;
  attained: string;
  issued_by: string;
}

export interface Company extends StrapiDocument {
  organization: SingleOrganizationComponent | null;
  experiences: Experience[];
}

export interface Education extends StrapiDocument {
  school: School | null;
  course: string;
}

export interface Experience extends StrapiDocument {
  company: Company | null;
  position: string;
  responsibilities: ArrayListComponent[];
}

export interface Info extends StrapiDocument {
  position: string;
  phone_number: string;
  email: string;
  address: string;
  nationality: string;
  visa: string;
  summary: string;
  links: ArrayLinkComponent[];
  first_name: string;
  last_name: string;
  middle_name: string;
}

export interface Language extends StrapiDocument {
  language: string;
  level: string;
}

export interface Meta extends StrapiDocument {
  title: string;
  description: string;
  keywords: ArrayListComponent[];
}

export interface Project extends StrapiDocument {
  name: string;
  description: string;
  tech_stack: ArrayListComponent[];
  links: ArrayLinkComponent[];
}

export interface Reference extends StrapiDocument {
  name: string;
  position: string;
  email: string | null;
  phone_number: string;
  relationship: string;
  company: string;
}

export interface School extends StrapiDocument {
  organization: SingleOrganizationComponent | null;
  educations: Education[];
}

export interface TechnicalSkill extends StrapiDocument {
  category: string;
  skills: ArrayListComponent[];
}

interface ResponseMeta {
  pagination?: {
    page: number;
    pageSize: number;
    pageCount: number;
    total: number;
  };
}

export type SingleResponse<T> = { data: T; meta: ResponseMeta };
export type CollectionResponse<T> = { data: T[]; meta: ResponseMeta };
